spring:
  # 数据库配置
  datasource:
    url: jdbc:h2:mem:mallqdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
        default-requeue-rejected: false
    template:
      retry:
        enabled: true
        initial-interval: 2000
        max-attempts: 3

# 服务器配置
server:
  port: 8080 